### ISSUE TITLE
Background operation stops after some minutes

### ISSUE THREAD

**Issue by JuanCAlpizar** [hazemhagrass/phonegap-background#5]
Hello, I have a phonegap application that needs to check for notifications every amount of X minutes based on user preferences, so I thought about using this plugin to make it.

My problem is that `LockBackgroundTime` doesn't seems to run infinitely, I put a console log every second to check it out, and after around 3 minutes the console stops printing.

Same happens when I use `              window.plugins.BackgroundJS.SetBackgroundSeconds(310, function(){}, function(msg){console.log(msg);});` once it gets around 180 seconds the console stops printing and the conditions inside never happens while the application is on the background.

I'm testing on an iPhone 4S with iOS 7.1

am I doing something wrong or is this a bug?

**Comment by bottasergio** [comment]
@JuanCAlpizar Did you solve this problem? Is it possible to run a background task on iOS to check server for  a long time?

**Comment by christocracy** [comment]
This restriction is not a problem -- it's s protection against developers killing the user's battery.

There is NO way to keep the CPU spinning in background on iOS unless you declare a UIBackgroundMode, such as "location" or "audio".  

If you do declare a UIBackgroundMode, you better be making an app related to to that mode (eg if you declare "audio" and you're not making something like a music player, you're screwed; Apple will reject you).  Or if you declare the "location" mode, like my plugin cordova-background-geolocation, you better be making a fleet-tracking/jogging app or something.  https://github.com/transistorsoft/cordova-background-geolocation-lt

The solution is to have your server do the polling, sending silent push requests to devices.

**Comment by JuanCAlpizar** [comment]
@bottasergio as @christocracy  said, it's a system limitation, why it does it it's a different topic (no way it's a system protection, just take a look at project Doze from Google, apps can always run in background and the system regulates this lol but they're never killed and even before Doze I had phones with 5.5 screen on time hours and 24 hours per charge cycle) in the end I went for the silent push notifications. 

I'm closing this because there's basically nothing the developer can do about it unless iOS change its policy on the matter. 

Cheers

**Comment by bottasergio** [comment]
What about https://github.com/edewit/cordova-background-plugin that implements "Background fetch" as Apple says on https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html ... "Background fetch ... The app regularly downloads and processes small amounts of content from the network." ??

**Comment by christocracy** [comment]
`cordova-background-plugin` won't do it.  I made a [background-fetch implementation](https://github.com/christocracy/cordova-plugin-background-fetch) too.

iOS background-fetch is nice, bit it will only awaken your app about every 15min (during primetime hours, less often when you're presumed to be sleeping), providing your app **exactly** 30s of background-running.  Once the 30s  elapses, your app is back to sleep.

**Comment by bottasergio** [comment]
@christocracy During the 30 seconds, is it possible to retrieve data from a web server and show a notification to the user if there is new info?

**Comment by christocracy** [comment]
And just in case anyone ever gets tempted to use `cordova-plugin-background-mode`, just search its issues for ["rejection"](https://github.com/katzer/cordova-plugin-background-mode/issues?utf8=%E2%9C%93&q=reject+) -- nothing but tears.  

100% **guaranteed** Apple rejection

**Comment by christocracy** [comment]
@bottasergio That's exactly the purpose.  You can do whatever you wish.

If you had a sports app, for example, you'd refresh the scores every 15min in background so that when user opens the app again, it's relatively fresh data.

**Comment by bottasergio** [comment]
@christocracy which plugin you recommend to use to notify user that new info is available?
I have to use it before " Fetcher.finish(); " right?

**Comment by bottasergio** [comment]
Have you tried onesignal.com ? Excellent service and support. Works on iOs and Android with no problem! And it is free!

**Comment by christocracy** [comment]
How about this?

https://apps.ionic.io/landing/push

On Monday, November 9, 2015, bottasergio notifications@github.com wrote:

> Have you tried onesignal.com ? Excellent service and support. Works on
> iOs and Android with no problem! And it is free!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hazemhagrass/phonegap-background/issues/5#issuecomment-155220015
> .

## 

Snet form Gmail Mobile

**Comment by bottasergio** [comment]
Bad beginning ... "500: Server Error . We broke something! Our team has been notified and we will be fixing the issue shortly." when registering!
